// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZebraIoTConnector.Persistence;

#nullable disable

namespace ZebraIoTConnector.Persistence.Migrations
{
    [DbContext(typeof(ZebraDbContext))]
    [Migration("20260105143835_AddAssetTags")]
    partial class AddAssetTags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AcquisitionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BusinessArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDiscoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDiscoveredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TechnicalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetNumber")
                        .IsUnique();

                    b.HasIndex("CostCenter");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("LastDiscoveredAt");

                    b.HasIndex("Plant");

                    b.HasIndex("TagIdentifier")
                        .IsUnique()
                        .HasFilter("[TagIdentifier] IS NOT NULL");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.AssetMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("int");

                    b.Property<string>("ReaderIdString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("GateId");

                    b.HasIndex("ReadTimestamp");

                    b.HasIndex("ReaderId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("AssetMovements");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.AssetTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMobile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ReferenceStorageUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ReferenceStorageUnitId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.InventoryOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("StorageUnitFromId")
                        .HasColumnType("int");

                    b.Property<int>("StorageUnitToId")
                        .HasColumnType("int");

                    b.Property<int>("SublotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("StorageUnitFromId");

                    b.HasIndex("StorageUnitToId");

                    b.HasIndex("SublotId");

                    b.ToTable("InventoryOperation");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.StorageUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StorageUnits");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Sublot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StorageUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("StorageUnitId");

                    b.ToTable("Sublots");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Asset", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.AssetMovement", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Asset", "Asset")
                        .WithMany("Movements")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Equipment", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("FromLocation");

                    b.Navigation("Gate");

                    b.Navigation("Reader");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.AssetTag", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Asset", "Asset")
                        .WithMany("Tags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Equipment", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Gate", "Gate")
                        .WithMany("Readers")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "ReferenceStorageUnit")
                        .WithMany()
                        .HasForeignKey("ReferenceStorageUnitId");

                    b.Navigation("Gate");

                    b.Navigation("ReferenceStorageUnit");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Gate", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Site", "Site")
                        .WithMany("Gates")
                        .HasForeignKey("SiteId");

                    b.Navigation("Location");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.InventoryOperation", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "StorageUnitFrom")
                        .WithMany()
                        .HasForeignKey("StorageUnitFromId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "StorageUnitTo")
                        .WithMany()
                        .HasForeignKey("StorageUnitToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZebraIoTConnector.Persistence.Entities.Sublot", "Sublot")
                        .WithMany()
                        .HasForeignKey("SublotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("StorageUnitFrom");

                    b.Navigation("StorageUnitTo");

                    b.Navigation("Sublot");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Sublot", b =>
                {
                    b.HasOne("ZebraIoTConnector.Persistence.Entities.StorageUnit", "StorageUnit")
                        .WithMany()
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Asset", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Gate", b =>
                {
                    b.Navigation("Readers");
                });

            modelBuilder.Entity("ZebraIoTConnector.Persistence.Entities.Site", b =>
                {
                    b.Navigation("Gates");
                });
#pragma warning restore 612, 618
        }
    }
}
